### ISSUE TITLE
Error response from daemon: reference does not exist

### ISSUE THREAD

**Issue by rubenanapu** [brthor/docker-save-last-layer#1]
Following the suggestion on https://stackoverflow.com/a/55527234/6490637, I tried to export the last layer of an image and I always get the mentioned in the title.

How could I enable debug mode or somehow bypass this error?

```
sudo d-save-last -o testing.tar ruben_last_layer:latest 

Running dind-save container...
Running docker save...
Command failed with exit code: 1

Error response from daemon: reference does not exist

Cleaning up...

```

The `ruben_last_layer:latest` is just a `ubuntu:18.04` image with `vim` installed.

**Comment by rubenanapu** [comment]
Ok, I mananged to solve it after changing docker to use `overlay2` following https://docs.docker.com/storage/storagedriver/overlayfs-driver/

# Changing docker to use Overlay2

1. `sudo systemctl stop docker`
2. Add the content below to `/etc/docker/daemon.json`;
```
{
  "storage-driver": "overlay2"
}
```
3. `sudo systemctl start docker`
4. `docker info`

# Pulling new images

After changing to `overlay2`, I run `docker images` and no image was found.
So I just downloaded `ubuntu:18.04` with `docker pull ubuntu:18.04`, then ran the image and installed `vim`.

Then I could save the new image without any problems with:
```
 sudo d-save-last vim_installed:latest  -o vim_insatlled_layer.tar
```

**Comment by brthor** [comment]
Thanks for filing this @rubenanapu . 

I double checked, The caveat requiring `overlay2` is listed in the docs but this is great documentation for the actual error that occurs.
